package com.ricky.mall.mybatis.model;

import java.io.Serializable;

public class PmsBrand implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_brand.id
     *
     * @mbggenerated Mon Mar 16 17:45:38 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_brand.name
     *
     * @mbggenerated Mon Mar 16 17:45:38 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_brand.first_letter
     *
     * @mbggenerated Mon Mar 16 17:45:38 CST 2020
     */
    private String firstLetter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_brand.big_pic
     *
     * @mbggenerated Mon Mar 16 17:45:38 CST 2020
     */
    private String bigPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_brand.brand_story
     *
     * @mbggenerated Mon Mar 16 17:45:38 CST 2020
     */
    private String brandStory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_brand
     *
     * @mbggenerated Mon Mar 16 17:45:38 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_brand.id
     *
     * @return the value of pms_brand.id
     *
     * @mbggenerated Mon Mar 16 17:45:38 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_brand.id
     *
     * @param id the value for pms_brand.id
     *
     * @mbggenerated Mon Mar 16 17:45:38 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_brand.name
     *
     * @return the value of pms_brand.name
     *
     * @mbggenerated Mon Mar 16 17:45:38 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_brand.name
     *
     * @param name the value for pms_brand.name
     *
     * @mbggenerated Mon Mar 16 17:45:38 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_brand.first_letter
     *
     * @return the value of pms_brand.first_letter
     *
     * @mbggenerated Mon Mar 16 17:45:38 CST 2020
     */
    public String getFirstLetter() {
        return firstLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_brand.first_letter
     *
     * @param firstLetter the value for pms_brand.first_letter
     *
     * @mbggenerated Mon Mar 16 17:45:38 CST 2020
     */
    public void setFirstLetter(String firstLetter) {
        this.firstLetter = firstLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_brand.big_pic
     *
     * @return the value of pms_brand.big_pic
     *
     * @mbggenerated Mon Mar 16 17:45:38 CST 2020
     */
    public String getBigPic() {
        return bigPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_brand.big_pic
     *
     * @param bigPic the value for pms_brand.big_pic
     *
     * @mbggenerated Mon Mar 16 17:45:38 CST 2020
     */
    public void setBigPic(String bigPic) {
        this.bigPic = bigPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_brand.brand_story
     *
     * @return the value of pms_brand.brand_story
     *
     * @mbggenerated Mon Mar 16 17:45:38 CST 2020
     */
    public String getBrandStory() {
        return brandStory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_brand.brand_story
     *
     * @param brandStory the value for pms_brand.brand_story
     *
     * @mbggenerated Mon Mar 16 17:45:38 CST 2020
     */
    public void setBrandStory(String brandStory) {
        this.brandStory = brandStory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_brand
     *
     * @mbggenerated Mon Mar 16 17:45:38 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", firstLetter=").append(firstLetter);
        sb.append(", bigPic=").append(bigPic);
        sb.append(", brandStory=").append(brandStory);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}